
# install targets

install-client:
	install -D -d $(DESTDIR)/usr/bin
	install -D client/ds-backup.py $(DESTDIR)/usr/bin/
	install -D client/ds-backup.sh $(DESTDIR)/usr/bin/
	install -D -d $(DESTDIR)/etc
	install -D -m 644 client/cron-ds-backup.conf $(DESTDIR)/etc/cron.d/ds-backup

install-server:
	install -D -d $(DESTDIR)/usr/bin
	install -D server/postprocess.py $(DESTDIR)/usr/bin

install: install-client install-server

.PHONY: install-client install-server

# vim: noet sts=4 ts=4 sw=4 :
